### ISSUE TITLE
Issue tracking the TODO items for AMQP multiplexing and connection pooling E2E tests

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#839]
The following items are tracked using this issue ID:

- [ ] Implement proxy and mux tests.
- [ ] Check that expected exception is thrown for certain fault types.
- [ ] Test that all multiplexed devices recover after fault injection duration.
- [ ] Disabling all fault injection tests for multiplexed devices.

**Comment by prmathur-microsoft** [comment]
Please open these kind of items on TFS to track. These are updates to not released features and should be a task on TFS.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
